### ISSUE TITLE
希望增加siliconflow平台接口，或者可以自定义增加平台

### ISSUE THREAD

**Issue by lgf5090** [Richasy/Rodel.Agent#2]
siliconflow平台可以一个api_key使用多种模型，很方便，希望后面可以增加进来。 

https://siliconflow.cn

**Comment by Richasy** [comment]
我看了一下，Siliconflow 是支持 OpenAI 兼容接口的，这个可以参考 [代理与 API 兼容](https://agent.richasy.net/chat-config#%E4%BB%A3%E7%90%86%E4%B8%8E-api-%E5%85%BC%E5%AE%B9) 来进行支持，你可以在应用中自行添加模型。

**Comment by lgf5090** [comment]
刚才试了一下，确实可以，但是有一个问题就是如果用户同时也需要openai的服务的话，那就需要重新填写open的api_key和api地址，极其不方便。

![小幻功能建议1](https://github.com/Richasy/Rodel.Agent/assets/170180789/7b51696b-8d7d-4c1e-8feb-6e3a8bd8a8ba)
