### ISSUE TITLE
[Feature] markdown实时渲染、app语言、剪贴板弹窗

### ISSUE THREAD

**Issue by ITCJ** [Richasy/Rodel.Agent#25]
### 功能描述 / Feature Description

1. 使用了一段时间，感觉只缺少类似sider那样的选中弹窗来方便使用，浏览器插件可以做到这一点，但是无法在系统全局下使用，如pdf阅读器等等。sider的windows app做了这一个功能，但无法自定义模型了
![image](https://github.com/Richasy/Rodel.Agent/assets/33901467/c8d50a9f-a9b1-4a0a-a1d9-fd04287001df)

2. 模型上次使用记录。另外available service似乎不能记住之前选择的模型，再次对话时需要重新选择模型，需要保存到session present
![image](https://github.com/Richasy/Rodel.Agent/assets/33901467/d13d1507-750e-418f-b81b-c5dbea03c003)

3. app语言修改。由于我修改了操作系统的语言为en，导致rodel agent界面也只能为英语了，暂时找不到切换的地方
![image](https://github.com/Richasy/Rodel.Agent/assets/33901467/4bad50ba-8329-43d2-9616-418488e76cfc)

4. markdown的实时渲染。现有的输出在渲染后会发生排版大幅度变化，导致阅读中断

### 备选方案 / Alternatives

关于1、4可能的备选方案有
1. 对于剪贴板的自动读取
4. 维持原有的排版大小

**Comment by Richasy** [comment]
关于功能1，你是指希望在系统全局选中任意文本会出现弹窗吗？

**Comment by noangel2014** [comment]
这个功能是很好，豆包桌面版就有。最小化程序的情况下可以完成日常任务，不用每次都用对话框来完成。正确的做法是 这个应该是一个可开关可配置的功能。另外必须要可以排除某些程序下不启用，否则随便哪里选一下，就出来工具栏了，也蛮讨厌的。

**Comment by Richasy** [comment]
目前没有实现全局文本选择弹窗的计划。如果你对此有比较大的期待，可以再单开一个 Issue

P.S. 最好一个 Issue 只提出一个功能需求，不然不好追踪

**Comment by ITCJ** [comment]
> 关于功能1，你是指希望在系统全局选中任意文本会出现弹窗吗？

是的
