### ISSUE TITLE
[Feature] 支持 Gemini 代理地址

### ISSUE THREAD

**Issue by MangMax** [Richasy/Rodel.Agent#3]
希望可以自定义代理地址，有些国外的模型使用比较方便，类似lobe chat这种设置
![image](https://github.com/Richasy/Rodel.Agent/assets/68525017/7d5d3c84-950d-493a-9fe1-f6375254dd32)

**Comment by Richasy** [comment]
在小幻助理里叫终结点(API)，你可以在OpenAI设置里找到

**Comment by MangMax** [comment]
> 在小幻助理里叫终结点(API)，你可以在OpenAI设置里找到。
> 
> 话说你是特指Gemini要代理吗

不好意思，我一开始只尝试了Gemini没看到openai，确实我需要Gemini代理

**Comment by Richasy** [comment]
OK，下个版本加上

**Comment by MangMax** [comment]
> OK，下个版本加上

感谢！
