### ISSUE TITLE
[Feature] 能否直接提供下载地址

### ISSUE THREAD

**Issue by noangel2014** [Richasy/Rodel.Agent#32]
### 功能描述 / Feature Description

很多人的系统都是阉割过的，没办法从应用商店安装应用，比如俺。

**Comment by Richasy** [comment]
应用侧载现如今可能并不是一种推荐的方式，它不算安全，同时也不利于同步更新。

如果你的设备上没有 Microsoft Store，可以尝试下面的安装方式：

1. 打开 https://store.rg-adguard.net/
2. 在输入框中输入这个链接：https://www.microsoft.com/store/productId/9NB0NB3MLQTM ，然后按下回车
3. 等待一段时间后，你能看到一堆应用包。
    ![image](https://github.com/Richasy/Rodel.Agent/assets/27713596/ab5fad95-6487-472a-80a4-c2d6202b71fb)
4. 如果你是第一次安装，那么你需要先下载名为 `Microsoft.WindowsAppRuntime` 的包，找到最新的版本，下载适合你系统架构的包，比如 `x64`，注意，安装包的后缀需要是 `.msix`。
5. 在完成 Microsoft.WindowsAppRuntime 的安装后，你可以下载应用本体，文件名开头是 `60520B029E250.36001E4C9CEE6（这个是小幻助理在应用商店里的ID），同样下载适合你设备的 msix 包，然后安装即可。

P.S. 我不太确定这个流程是否能在定制系统中工作，你可以试一下，然后给我一个反馈。

**Comment by noangel2014** [comment]
不行，认不出.msix。我系统是网上常见的精简版系统，应用商店被删了。装个应用商店应该可以用吧，懒的试了

**Comment by Richasy** [comment]
那应该是你的系统把 [App Installer](https://www.microsoft.com/store/productId/9NBLGGH4NNS1?ocid=pdpshare) 也给精简掉了。如果你下载了 Microsoft Store，可能还需要下载 App Installer

**Comment by cornradio** [comment]
我发现我把屏蔽掉的windows updater 启用就能安装了。
