### ISSUE TITLE
希望增加四个功能建议

### ISSUE THREAD

**Issue by lgf5090** [Richasy/Rodel.Agent#4]
如图所示：
![小幻助理功能建议2](https://github.com/Richasy/Rodel.Agent/assets/170180789/0ef5d257-5bce-4ec5-8a2f-03dbae76e233)

**Comment by Richasy** [comment]
感谢建议。

1. 快捷指令和“助理”功能重复，本质上就是一个系统提示词的快照，助理还支持参数设置，理论上自定义能力更强。所以没有很强的理由像 NextChat 这样添加“快捷指令”。
2. 小幻助理是一个 AI 应用，主要用于集成各种 AI 服务。简单的笔记功能没有太大的必要加进小幻助理之中。有一种情况是使用 在笔记场景里加入 AI 续写文本。但这需要更多的思考，而不是简单地添加，短期内可能不会考虑。
3. 搜索功能在计划内，我正在计划一个全局搜索功能，可以搜索服务/助手/会话内容/图片信息等，这个会在之后实装
