### ISSUE TITLE
[Feature] 希望每一个助理的右侧选项兰中增加一个存放笔记的栏目

### ISSUE THREAD

**Issue by lgf5090** [Richasy/Rodel.Agent#41]
### 功能描述 / Feature Description

 希望每一个助理的右侧选项兰中增加一个存放笔记的栏目，最近使用遇到一个问题，每一个助理我们都需要不断的调试提示词然后测试一些固定的问题使它与自己期望的结果越吻合。所以提示词可能会不定期更新因为自己的需求变化，结果忘了之前提问了哪些问题。每一个助理都附带一个note信息记录自己的调试问题就非常的方便，助理一多这个问题就更凸显了。

**Comment by Richasy** [comment]
针对这个使用场景，请使用会话预设功能。

即不急着创建助理，而是起一个单独的会话，调试提示词，你可以点击右上角的保存按钮来保存当前会话的快照

![image](https://github.com/Richasy/Rodel.Agent/assets/27713596/dec48480-97f2-44d2-8f8e-89bcb6aa921f)

具体参考：[会话预设](https://agent.richasy.net/agent-preset#%E4%BC%9A%E8%AF%9D%E9%A2%84%E8%AE%BE)
