### ISSUE TITLE
[Feature] 支持豆包大模型

### ISSUE THREAD

**Issue by Richasy** [Richasy/Rodel.Agent#47]
### 功能描述 / Feature Description

火山引擎近日开放了豆包大模型的第三方API调用，应予以支持

**Comment by lgf5090** [comment]
豆包大模型咋没有内置模型呢？我自己安装官方文档写入自定义模型，但是一直提示错误。是我哪里设置不对吗？
官方文档：
![image](https://github.com/Richasy/Rodel.Agent/assets/170180789/774d7fbb-8b40-4faf-962b-fb9d0e6cfcf7)

自定义模型设置：
![image](https://github.com/Richasy/Rodel.Agent/assets/170180789/145a23cb-f960-411e-84b5-a860e262df64)

错误显示信息：
![image](https://github.com/Richasy/Rodel.Agent/assets/170180789/cf08696c-76fd-43fc-9dbe-7fd45423db3e)
