### ISSUE TITLE
希望头像设置功能可以丰富一点

### ISSUE THREAD

**Issue by lgf5090** [Richasy/Rodel.Agent#5]
如下如所示：

![小幻助理功能建议4](https://github.com/Richasy/Rodel.Agent/assets/170180789/3c2ac28f-a236-42f0-a872-77d278674f44)

![image](https://github.com/Richasy/Rodel.Agent/assets/170180789/680b5f51-86b0-44c7-971e-55ba29b144af)

![image](https://github.com/Richasy/Rodel.Agent/assets/170180789/54a46fa0-4415-40fb-9cbe-4b09b9429f02)

**Comment by Richasy** [comment]
很好的建议，后续我会看如何实现它
