### ISSUE TITLE
[Feature] 希望可以添加类似poe平台上可以在同一个窗口调用不同的助手进行对话

### ISSUE THREAD

**Issue by lgf5090** [Richasy/Rodel.Agent#50]
### 功能描述 / Feature Description

希望可以添加类似poe平台上可以在同一个窗口调用不同的助手进行对话。

通过"@"符号列出所有的助手，并将问题传递给该助手并返回结果。体验了一周左右，感觉这个功能挺实用的，可以不用在多个助手来回查看对比。

![image](https://github.com/Richasy/Rodel.Agent/assets/170180789/81b6dee6-e627-4c44-863a-7e5aa719408e)

**Comment by Richasy** [comment]
与 #21 重复
