### ISSUE TITLE
[Bug] 运行报错缺少  config.json,, 是否能提供样例

### ISSUE THREAD

**Issue by icetech233** [Richasy/Rodel.Agent#51]
### Bug 描述 / Description

[Bug] 运行报错缺少  config.json,, 是否能提供阳历

### 复现问题的步骤 / Steps to reproduce

```plain text
[Bug] 运行报错缺少  config.json,, 是否能提供阳历
```

### 预期行为 / Expected behavior

[Bug] 运行报错缺少  config.json,, 是否能提供阳历

### 系统版本

- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明) / Other (Specify)

### 其它系统版本 / Other system version

13

### 日志记录 / Log

[Bug] 运行报错缺少  config.json,, 是否能提供阳历

### 备注 / Additional context

[Bug] 运行报错缺少  config.json,, 是否能提供阳历

**Comment by Richasy** [comment]
参考 ReadMe 中的说明手动编写 config.json

**Comment by icetech233** [comment]
> 参考 ReadMe 中的说明手动编写 config.json

看了C# class源码 ，我明白了
