### ISSUE TITLE
希望每一个助理都可以选择并锁定指定模型

### ISSUE THREAD

**Issue by lgf5090** [Richasy/Rodel.Agent#6]
如图所示：

![小幻助理功能建议3](https://github.com/Richasy/Rodel.Agent/assets/170180789/c0deb56e-9bfd-42ef-84de-6749721a4d2f)

**Comment by Richasy** [comment]
会在后续版本中实现

**Comment by MinionsZQG** [comment]
是的，非常同意，辛苦作者啦
