### ISSUE TITLE
[Bug] Ollama设置、调用无效

### ISSUE THREAD

**Issue by MangMax** [Richasy/Rodel.Agent#67]
### Bug 描述 / Description

无法正确配置和调用Ollama

1.配置终结点后切换页面返回时配置的字符串不见了，查看数据库貌似是已经保存了可能是读取有问题
2.参考了lobechat将终结点设置成`http://localhost:11434`，模型名称为gemma2:2b，id也为为gemma2:2b，不确定是不是要这个
![image](https://github.com/user-attachments/assets/dad98c86-2905-4db3-a54a-c52ad81e8709)
总之两个id都试了，结果都是返回404
3.需要更详细的配置说明，由于占位符填写的是openai的比较迷惑，ollama有两个api`http://localhost:11434/api/chat`
`http://localhost:11434/api/generate`,不清楚填`http://localhost:11434`还是`http://localhost:11434/api`还是别的，
4.是否可以增加自动从ollama获取模型列表，这样可以降低配置错误的概率

### 复现问题的步骤 / Steps to reproduce

```plain text
本地部署ollama运行模型，配置ollama地址和模型
```

### 预期行为 / Expected behavior

正确返回答案

### 截图 / Screenshots

![PixPin_2024-08-04_23-30-29](https://github.com/user-attachments/assets/dda8f88b-79e1-45b9-b1a4-e27ab134b601)

### 系统版本

- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [X] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明) / Other (Specify)

### 运行设备 / Running device

桌面（个人电脑） / Desktop (Personal Computer)

### 日志记录 / Log

[applog.2024-08-04.log](https://github.com/user-attachments/files/16488082/applog.2024-08-04.log)

**Comment by Richasy** [comment]
这里是详细文档：https://agent.richasy.net/chat-config#ollama
你需要填写的 api 地址是：http://localhost:11434/v1
