### ISSUE TITLE
[Bug] 隐藏窗口再打开，关闭按钮为红色

### ISSUE THREAD

**Issue by ghost** [Richasy/Rodel.Agent#71]
### Bug 描述 / Description

点击右上角X的行为选择的是隐藏到托盘。此bug在完全退出应用，然后再次进入时得到解决，但仍有概率复现。

### 复现问题的步骤 / Steps to reproduce

```plain text
打开应用。
```

### 预期行为 / Expected behavior

解决bug。

### 截图 / Screenshots

![屏幕录制 2024-09-15 184513](https://github.com/user-attachments/assets/1bed2b0d-bd66-48ee-b0b2-5ae801e73c90)

### 系统版本

- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明) / Other (Specify)

### 运行设备 / Running device

桌面（平板或笔记本） / Desktop (Tablet or Laptop)

**Comment by internacionalismo** [comment]
![屏幕录制 2024-09-15 184513](https://github.com/user-attachments/assets/ba2d428e-40a2-43f2-9fa3-e4544de950e1)

**Comment by internacionalismo** [comment]
![屏幕截图 2024-09-16 092350](https://github.com/user-attachments/assets/9d5ef06e-1957-4f19-ac18-0d313a4d2373)

**Comment by Richasy** [comment]
这应该是一个 winui 的bug，隐藏窗口时如果此时光标位于关闭按钮上，则界面恢复时需要手动划一下关闭按钮来更新UI。
从应用这一侧应该做不了什么，后续如果 winui 进行了修复，这边会跟进
