### ISSUE TITLE
[Bug] 配置webdav的时候出现空白下拉栏和配置项丢失

### ISSUE THREAD

**Issue by BiliBili-ACEGE** [Richasy/Rodel.Agent#72]
### Bug 描述 / Description

空白下拉栏：
![image](https://github.com/user-attachments/assets/371cac8f-6833-4b6a-bdb8-ff4a86be10f8)

当多次配置之后重启软件立刻展开webdav的选项，就会有概率发生配置项目丢失的问题：
![image](https://github.com/user-attachments/assets/ee30486d-9f57-488e-bba9-f78ca5ba2933)

另外配置一直说无效：
![image](https://github.com/user-attachments/assets/0bf627fa-c3cf-4eaa-ae21-c31b6a0b55d1)
但是我确认没有配置出错，我是使用手机开启alist服务，然后电脑在软件里面配置，电脑浏览器可以正常访问

### 复现问题的步骤 / Steps to reproduce

```plain text
多次配置webdav之后，重启软件打开下拉栏即可
```

### 预期行为 / Expected behavior

修复bug

### 截图 / Screenshots

![image](https://github.com/user-attachments/assets/4bcb351d-accd-4ec3-8d09-1bce5cd364b7)
![image](https://github.com/user-attachments/assets/290fb6ed-692c-4891-ae7d-c2674176c026)

### 系统版本

- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明) / Other (Specify)

**Comment by Richasy** [comment]
你发错仓库了
